### ISSUE TITLE
Menu Should Move Page Content Out of the Way

### ISSUE THREAD

**Issue by mzagaja** [MAPC/digitalhub#35]
The menu should move the page content to the left when it opens on desktop view.

**Comment by ericyoungberg** [comment]
If you need an assist on this, [my website](https://ericyoungberg.com) does this. [[Source code]](https://github.com/MAPC/digitalhub/files/2385655/ericyoungberg-personal-3da00960dad0.zip)

The state of equity site does something somewhat similar, but that site shoves the content instead of squishing it.
