### ISSUE TITLE
Event Prompt Style Fix

### ISSUE THREAD

**Issue by smithWEBtek** [MAPC/digitalhub#360]
Kit Un:   Not major but can someone fix the padding and cut off when they have a chance.

![events-prompt-fix](https://user-images.githubusercontent.com/16054332/62134765-19009400-b2af-11e9-8c4b-ba16fe465cc2.png)

**Comment by smithWEBtek** [comment]
<img width="562" alt="events" src="https://user-images.githubusercontent.com/16054332/62628882-21ce1700-b8fa-11e9-8950-49030dcdb1e6.png">

**Comment by theryankelly** [comment]
- Box should display nest three events
- Location in this case "webinar" should be on line two with a pipe delimited

**Comment by smithWEBtek** [comment]
The existing code works if you use the "City" field for location (in hubadmin). 
However the titles have to be unique, so we may need to figure out another solution to keep unique titles and prevent titles from taking up 2 lines.

**Comment by atomtay** [comment]
I grabbed some of the CSS that's creating the scroll effect on for the announcements and applied it to the events box on a [att/360-event-prompt-style-fix](https://github.com/MAPC/digitalhub/tree/att/360-event-prompt-style-fix) branch. It's still rough (no responsive styling applied yet) but wanted to throw it out there as an option.

![Screenshot_2019-08-13 MetroCommon 2050(1)](https://user-images.githubusercontent.com/10645500/62962161-547d8100-bdcc-11e9-8127-e0a4b4634d64.png)

**Comment by theryankelly** [comment]
I have adjusted the current event text to keep it to two lines.  Knowing the long titles our events can have this may not always be an option.  
![Screen Shot 2019-08-13 at 2 10 50 PM](https://user-images.githubusercontent.com/2421382/62966097-53505200-bdd4-11e9-8024-c21a8d70ca50.png)

I think the announcement scroll with the transparent styling to match the announcement and page scroll bars might be our best option.  Maybe we can be quick to break to a centered and prominent "Join us for an event!" link rather than events on mobile.  Current mobile (screenshot) looks to still want events. Center and provide a link to event page might be enough, rather than trying to make events fit.
![Screen Shot 2019-08-13 at 2 13 00 PM](https://user-images.githubusercontent.com/2421382/62966430-0325bf80-bdd5-11e9-8e13-414a137ddc64.png)

**Comment by atomtay** [comment]
Agree re: the quick break to the mobile styling; the XD file features rectangular cards as opposed to squares, but that could perhaps be expanded to tablets as well to ensure everything fits comfortably:

![Screen Shot 2019-08-13 at 2 37 43 PM](https://user-images.githubusercontent.com/10645500/62968002-21d98580-bdd8-11e9-9993-a21b24aa3f62.png)
