### ISSUE TITLE
Find Out Banner: Missing Images

### ISSUE THREAD

**Issue by theryankelly** [MAPC/digitalhub#376]
**Describe the bug**
The banner of the Find Out page is missing icons.  Goal is to have it resemble the XD 032719 Digital Hub 3.0 file. Need to determine if it is the image file or how the file is being stretched.

**Steps to reproduce**
Go to /find-out

**Expected behavior**

**Screenshots**
https://user-images.githubusercontent.com/16054332/61960662-e0ea1000-af93-11e9-981d-3e8bb935ceee.png

NOTE: 
I observe this when zooming way out, as if the image is "tiled": 

![background-tiled](https://user-images.githubusercontent.com/16054332/62626537-9a7ea480-b8f5-11e9-8089-0fc81f54bfde.png)

**Comment by atomtay** [comment]
It looks like the issue is in the image file itself as opposed to any in-browser stretching. I opened the XD file and exported the overlay as a PNG (as the current version is).

Exported example:
![Export-test](https://user-images.githubusercontent.com/10645500/62571590-bd5e7980-b85f-11e9-9c17-c48705da29d6.png)

Current version ('group-2111.png'):
![Current header](https://raw.githubusercontent.com/MAPC/digitalhub/develop/app/assets/images/group-2111.png)

I'm still trying to figure out how to make Ruby work on my machine (so I haven't verified this yet), but I think that including the exported example in `app/assets/images`, then you could edit line 53 of `app/assets/stylesheets/refinery/find_out.scss` to swap out the images:

```
  .find-out__header {
    @include media(small) {
      background: none;
    }
    background-image: image-url('new-image-name.png');
    height: 29.05rem;
  }
```

Still doesn't answer the underlying "why" (I would need to learn more about XD and how the larger export process works) but perhaps a start?
