### ISSUE TITLE
Change Dynamic Government AA Image

### ISSUE THREAD

**Issue by theryankelly** [MAPC/digitalhub#583]
The current image of Dynamic Gov AA is repetitive with Policy Recommendation. It also does not fit well in AA banner. 

- [ ] Should find a replacement image 
- [x] Adjust PDF to match (will not update pdf to match)

Current image:
![1802STEQUITY235](https://user-images.githubusercontent.com/2421382/137218193-8adb9ba8-5acd-444d-a37f-fdaa2b9cf688.jpg)

**Comment by theryankelly** [comment]
related to #561

**Comment by theryankelly** [comment]
@elisemaeharmon identifying state house image to replace the current. Will not update PDF

**Comment by elisemaeharmon** [comment]
@theryankelly: Giving you a few options here since I'm unsure what will look best with the banner:

- https://www.mapc.org/wp-content/uploads/2021/10/massachusetts-state-house-boston-scaled.jpg (possibly crop to show the "Massachusetts State House" text on the gate?) 
- https://www.mapc.org/wp-content/uploads/2021/12/AdobeStock_419769359-scaled.jpeg 
- https://www.mapc.org/wp-content/uploads/2021/12/AdobeStock_312989317-scaled.jpeg 
- https://www.mapc.org/wp-content/uploads/2021/12/AdobeStock_139358090-scaled.jpeg

**Comment by theryankelly** [comment]
My pick is AdobeStock_312989317-scaled.jpeg

I think it lends itself to the wide bar where it will live 
![image](https://user-images.githubusercontent.com/2421382/145899268-73f04963-6b7b-414b-ac3d-c96a3982f137.png)

- [ ] @trust-kimberly please update the AA header and let me know if you run into any issues with formatting.

**Comment by trust-kimberly** [comment]
Currently: 
![Screen Shot 2021-12-15 at 2 57 22 PM](https://user-images.githubusercontent.com/62153141/146256279-9c97880d-9c48-4081-a497-057990d87d64.png)

With the newer hero:
![Screen Shot 2021-12-15 at 2 57 04 PM](https://user-images.githubusercontent.com/62153141/146256347-23b6ce8f-ea97-478b-8485-aa403c1f451a.png)

Because the height is quite narrow, it may be hard to get the sense of the building, but I do still think it works better as a more abstract image.

**Comment by theryankelly** [comment]
What dimensions are needed? We can pre crop the image to better center align.
![312989317-scaled_mid](https://user-images.githubusercontent.com/2421382/146273576-f6d8597c-c424-403e-afd0-e877e9186bbe.png)

**Comment by theryankelly** [comment]
@trust-kimberly current staging still looks like old? Change still need to be pushed?
![image](https://user-images.githubusercontent.com/2421382/146409970-abeeae76-d9ef-4468-9f30-a188b2fb8e09.png)
